CREATE TABLE Users (
    idUser NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    password VARCHAR2(50) NOT NULL,
    email VARCHAR2(50) NOT NULL,
    status NUMBER(1,0)DEFAULT 1 NOT NULL  
);



CREATE TABLE Company (
    idCompany NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(50) NOT NULL,
    email VARCHAR2(50) NOT NULL,
    phone CHAR(10) NOT NULL,
    address VARCHAR2(50) NOT NULL,
    identificationNumber VARCHAR2(50) NOT NULL,
    idSector NUMBER NOT NULL,
    status NUMBER(1,0) DEFAULT 1 NOT NULL ,
    idUserCreate NUMBER NULL,
    dateCreate DATE NULL,
    idUserModified NUMBER NULL,
    dateModified DATE NULL,
    CONSTRAINT PK_Company PRIMARY KEY (idCompany)
);


CREATE TABLE ComplementaryActivity (
    idComplementaryActivity NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    activityname VARCHAR2(50) NOT NULL,
    status NUMBER(1,0) DEFAULT 1 NOT NULL,
    idStudent NUMBER NOT NULL,
    idActivityType NUMBER NOT NULL,
    idusercreate NUMBER NULL,
    datecreate DATE NULL,
    idusermodified NUMBER NULL,
    datemodified DATE NULL,
    CONSTRAINT PK_ComplementaryActivity PRIMARY KEY (idComplementaryActivity)
);

CREATE TABLE ComplementaryActivityCompany (
    idComplementaryActivityCompany NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    idComplementaryActivity NUMBER NOT NULL,
    IdCompany NUMBER NOT NULL,
    status NUMBER(1,0) DEFAULT 1 NOT NULL,
    idUsercreate NUMBER NULL,
    datecreate DATE NULL,
    idusermodified NUMBER NULL,
    datemodified DATE NULL,
    CONSTRAINT PK_ComplementaryActivityCompany PRIMARY KEY(idComplementaryActivityCompany)
);

CREATE OR REPLACE PROCEDURE ObtenerDatosComplementaryActivityCompany(
    resultados OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN resultados FOR
        SELECT
            cac.idComplementaryActivityCompany,
            c.idcompany AS idcompany,
            c.name AS name,
            cac.idcomplementaryactivity AS idcomplementaryactivity,
            ca.activityname AS activityname
        FROM
            ComplementaryActivityCompany cac
        INNER JOIN
            Company c ON cac.idcompany = c.idcompany
        INNER JOIN
            ComplementaryActivity ca ON cac.idcomplementaryactivity = ca.idcomplementaryactivity;
END ObtenerDatosComplementaryActivityCompany;
/

INSERT INTO Users (name,password, email)
VALUES ('Nallely', '123','toledo@');

INSERt INTO Company(name,email,phone,address,identificationNumber,idSector,idUserCreate,dateCreate,idUserModified,dateModified)
VALUES('Altos hornos de mexico','hornos@gmail.com','8661652344','kenedy 122 monclova','2023',1,1,SYSDATE,1,SYSDATE);
INSERt INTO Company(name,email,phone,address,identificationNumber,idSector,idUserCreate,dateCreate,idUserModified,dateModified)
VALUES('Denso','denso@gmail.com','8661302344','de los hornos cd frontera','2023',2,1,SYSDATE,1,SYSDATE);
INSERt INTO Company(name,email,phone,address,identificationNumber,idSector,idUserCreate,dateCreate,idUserModified,dateModified)
VALUES('Ferromex','ferromex@gmail.com','8661623445','Americana cd frontera','2023',3,1,SYSDATE,1,SYSDATE);
INSERt INTO Company(name,email,phone,address,identificationNumber,idSector,idUserCreate,dateCreate,idUserModified,dateModified)
VALUES('Coahuila Durango','coahuiladurango@gmail.com','8662002344','porfirio diaz cd frontera','2023',4,1,SYSDATE,1,SYSDATE);
INSERt INTO Company(name,email,phone,address,identificationNumber,idSector,idUserCreate,dateCreate,idUserModified,dateModified)
VALUES('Aptiv','aptiv@gmail.com','8661702344','lib carlos salinas de gortari','2023',5,1,SYSDATE,1,SYSDATE);
	  
INSERt INTO ComplementaryActivity(activityname,idStudent,idActivityType,idUsercreate,dateCreate,idUserModified,dateModified)
VALUES('practice',1,1,1,SYSDATE,1,SYSDATE);
INSERt INTO ComplementaryActivity(activityname,idStudent,idActivityType,idUsercreate,dateCreate,idUserModified,dateModified)
VALUES('residence ',2,2,1,SYSDATE,1,SYSDATE);
INSERt INTO ComplementaryActivity(activityname,idStudent,idActivityType,idUsercreate,dateCreate,idUserModified,dateModified)
VALUES(' stay',3,3,1,SYSDATE,1,SYSDATE);
INSERt INTO ComplementaryActivity(activityname,idStudent,idActivityType,idUsercreate,dateCreate,idUserModified,dateModified)
VALUES('socialservice',4,4,1,SYSDATE,1,SYSDATE);	  
	  
INSERT INTO ComplementaryActivityCompany( idComplementaryActivity,IdCompany ,IdUserCreate,datecreate,idusermodified,datemodified)
Values (1,1,1,SYSDATE,1,SYSDATE);
INSERT INTO ComplementaryActivityCompany( idComplementaryActivity,IdCompany ,IdUserCreate,datecreate,idusermodified,datemodified)
Values (2,2,1,SYSDATE,1,SYSDATE);
INSERT INTO ComplementaryActivityCompany( idComplementaryActivity,IdCompany ,IdUserCreate,datecreate,idusermodified,datemodified)
Values (3,3,1,SYSDATE,1,SYSDATE);
INSERT INTO ComplementaryActivityCompany( idComplementaryActivity,IdCompany ,IdUserCreate,datecreate,idusermodified,datemodified)
Values (4,4,1,SYSDATE,1,SYSDATE);
INSERT INTO ComplementaryActivityCompany( idComplementaryActivity,IdCompany ,IdUserCreate,datecreate,idusermodified,datemodified)
Values (1,1,1,SYSDATE,1,SYSDATE);	  

